
# Use new container infrastructure to enable caching
#sudo: false

# Do not choose a language; we provide our own build tools.
language: python

python:
- 2.6

before_install:
- sudo apt-get update
- sudo apt-get install apt-transport-https ca-certificates
- sudo apt-key adv \
               --keyserver hkp://ha.pool.sks-keyservers.net:80 \
               --recv-keys 58118E89F3A912897C070ADBF76221572C52609D 
- echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee /etc/apt/sources.list.d/docker.list
- sudo apt-get update
- apt-cache policy docker-engine
- sudo apt-get install docker-engine

install:
- echo "fine"
- true

script:
- |
  set -ex
  echo "still fine"
  set +ex


