
# Use new container infrastructure to enable caching
sudo: required

# Do not choose a language; we provide our own build tools.
language: python

services:
- docker

python:
- 2.6

env:
- REPO=phlummox/hask-bb-ci
- TAG=precise0.1
# DOCKER_USER
- secure: "JEtUEScS8FQIRfQEn5S56chpelyMu1if0Oc4VJiTJvcndkrDyYxV14OjiK+AEbHehXZ02YxJf+zyhfYujFFXGyUxok39QJ5e8CIF2EUGPSmH3vx2ZwdEfD6nYvY01GeqVH8BzASIBie9X0bo1R58byMhXo4OztY6M4zaSTDU+7pamMeMhGeuHDzkUONirgPiQuToZISnc1SoMUyR6JvC1qR/+IEfpIU1nCTYxYAzy32HIDdmp+bDGB1SI3XjMogzao70Y0ZtcJtNoWw8ZSdO1FjZPc/zUW6osre2SSkTBOy+5BXUZrJcxxCdJwfYYosR6eXKy/1xHIWu2E1E7K2RQcGvYXhtBIb1sDeZ+BkSj+jcDO+bPLNNGsvWVGOzzlE7cd6Tys3Cdt1rcIoGVDXkfcKIxZMHRWUgZ6FgK9VYgz5Fqvgspg4A/gkyPlecNe+FfOknTJ2Up3tjKZJOIjN1zwa63S7NorPw2MJ3XTnQ9oJco9JmN3BFuf9Oz6h61sbm1iMhQjqlwOw7iSzlxPXFIfcw131dnBoH8DikbYz7L2BnnbKLDPAPsilUhsuMrDn9o418IXtfFVee3+RZ+oxdmqM3F0tUIDOExmbeaWOYZ0erljfSihOn+XKf/mbiZOYuwPAHMV+PX3Msy3oAwSRemovAZLsQ+CaQvo0vJ9NJPGg=" 
# DOCKER_PASSWORD
- secure: "nf1IBnFwd78Y8OR16xPFzs+eTzoTn9soOFLpMnSpy77Rw9a3doQHustgsfDAlj4sUJ50Zm2O78ePRCB0opL9iet0pZmjQeWU0UTIc0rL9F0teo8wxqlDK6Nh6TQTqfZVivsEBWJl5415mb76riKjnB2CtwkbsC4LhlEvryT9bpi74Btkj5rmcwsCsZA0O3JImt55IK9U7w7iQOXS5zn9nG9bGxZfBRJVCNtMv0XYkdPa8dPZ+S3+k5bg7VpnrSm9GLnUNHmSOUk35nIiazR2F0MQ61qEiVdUjbQkhAGJaWPGGVVOAWV+fJhSpDq0wgTyuapQsfnN04GhDm1yyub3DP47l/QHZHgrkasMNqb6u2GMvo4GRZbYqH3FkrPw67f/ZLteHwaHtEP+cYtzGLMNS2opi262TOTXG3XC1pER+UqCi/1pIIoIowkRCkFBRUBo9V9nC5kLm9yMGwz+rdVSQgsDfk/NnSyMRJHuQGQItt5H/DaGMhE45HJJipBRAu9fc6rTXRtwrSYBrathhaoD0i46+4VdRf2GY2b6md46I2HVh3wcapLkyc3CSlG6j4QiABk1yqwv9q2mskXmuCzgP2iNfC0jn21lG0Vqx26/j86NJk/H9qatp6JzRmePbpXJW0E4s8kqYGHDABPNqJEz8BHXFkc0UJO7KK8amr+C56I="


install:
- docker build -t phlummox/hask-bb-ci:precise-v0.1 . 

script:
- result=$(docker images -q "$REPO":"$TAG");
- [ ! -z "$result" ]

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker push "$REPO":"$TAG" 

